# Generated by Django 5.1.6 on 2025-03-09 08:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0002_mediafile_google_uri_mediafile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.JSONField()),
                ('transcription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='transcription.transcription')),
            ],
        ),
    ]
