# Generated by Django 5.2 on 2025-05-20 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0005_update_existing_transcriptions_to_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcription',
            name='task_id',
            field=models.CharField(blank=True, help_text='Django Q task ID', max_length=255, null=True),
        ),
    ]
